'TechDivision.Jobs.ApplicationForm:ApplicationButton':
  superTypes:
    'Neos.Neos:Content': true
  ui:
    label: i18n
    group: 'jobs'
    icon: 'icon-briefcase'
    position: 'end'
    inspector:
      groups:
        general:
          label: 'General'
  properties:
    applicationFormNode:
      type: reference
      ui:
        label: i18n
        inspector:
          group: 'general'
          editorOptions:
            required: true
            nodeTypes: ['Neos.Neos:Document']
      validation:
        'Neos.Neos/Validation/NotEmptyValidator': []
