Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          TechDivision.Jobs.ApplicationForm:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        TechDivision.Jobs.ApplicationForm: true
